# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: bin/install-chrome
      - run: lein with-profile +test-common,+test-web,+dev deps
      - run: sudo bin/install-node && npm install

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run: lein check
      - run: lein with-profile test-common,clj-1.9.0-alpha17 test
      - run: lein with-profile test-common,clj-1.9.0-alpha18 test
      - run: lein with-profile test-common,clj-1.9.0-alpha19 test
      - run: lein with-profile test-common,clj-1.9.0-beta1 test
      - run: lein clean && lein with-profile test-web,cljs-1.9.562 cljsbuild once test && bin/tests
      - run: lein clean && lein with-profile test-web,cljs-1.9.908 cljsbuild once test && bin/tests
      - run: lein clean && lein with-profile test-web,cljs-1.9.946 cljsbuild once test && bin/tests